TRAIN:
  MODEL_NAME: 'UNet' #'UNet' # 'UNet', 'PointNet2', 'PointCNN', 'DGCNN', 'RandLA'
  OPTIMIZER: 'SGD' # 'SGD' or 'Adam'
  LEARNING_RATE: 0.06
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 4
  MAX_EPOCH: 50
  SCHEDULER: 'cos' # 'cos' or 'step' or 'LambdaLR'
  LEARNING_RATE_CLIP: 0.00001
  STEP_SIZE: 10 #
  LEARNING_RATE_DECAY: 0.5
  NESTEROV: True


  IS_PRETRAINED: False
  PRETRAINED_MODEL_PATH: checkpoints/pointnet2_MT.t7

  OUTPUT_DIR: log/
  DROPOUT_RATE: 0.7

  LOSS_FUNCTION: 'ConsistencyLoss' # ConsistencyLoss or HeirarchicalCrossEntropyLoss
  TRAIN_IGNORE_LABEL: 100
  CONSISTENCY_LOSS_EPOCH: 1000
  REG_FUNC: 'relu'  #'abs' or 'relu'


  DATASET: 'Urban3D'

  CONSISTENCY_LOSS_WEIGHT:
    - 1
    - 1
  LAYER_WEIGHTS:
    - 1
    - 0.6

DEVICES:
  GPU_ID: 
    - 0
  SEED: 1

