MAIN_DATA_PATH: '/root/autodl-tmp/PointCloudSegBase/data/campus3d_grid/'
MAIN_LABEL_PATH: '/root/autodl-tmp/PointCloudSegBase/data/campus3d_grid/'

TRAIN:
  - DATA_PATH:
      DATA: 'pcd/combined_0_1_0_1657154.pcd'
      LABEL: 'latest_label_12/combined_0_1_0_1657154.npy'
  - DATA_PATH:
      DATA: 'pcd/combined_42_48_2_1210180.pcd'
      LABEL: 'latest_label_12/combined_42_48_2_1210180.npy'
  - DATA_PATH:
      DATA: 'pcd/label_21_0-3-5_6113678.pcd'
      LABEL: 'latest_label_12/label_21_0-3-5_6113678.npy'
  - DATA_PATH:
      DATA: 'pcd/label_36_2-3_4518454.pcd'
      LABEL: 'latest_label_12/label_36_2-3_4518454.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_11_10_1-4_5055086.pcd'
#       LABEL: 'latest_label_12/combined_11_10_1-4_5055086.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_47_46_2-3_986973.pcd'
#       LABEL: 'latest_label_12/combined_47_46_2-3_986973.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_37_2-3_4746497.pcd'
#       LABEL: 'latest_label_12/label_37_2-3_4746497.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_4_9_1-4_3292117.pcd'
#       LABEL: 'latest_label_12/combined_4_9_1-4_3292117.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_23_0-1-3-5_7480162.pcd'
#       LABEL: 'latest_label_12/label_23_0-1-3-5_7480162.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_38_3-5_2025842.pcd'
#       LABEL: 'latest_label_12/label_38_3-5_2025842.npy'  
#   - DATA_PATH:
#       DATA: 'pcd/label_24_1-4-5_5040781.pcd'
#       LABEL: 'latest_label_12/label_24_1-4-5_5040781.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_44_2_3300147.pcd'
#       LABEL: 'latest_label_12/label_44_2_3300147.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_27_20_28_0-2-3_2309051.pcd'
#       LABEL: 'latest_label_12/combined_27_20_28_0-2-3_2309051.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_53_55_56_54_2_2367847.pcd'
#       LABEL: 'latest_label_12/combined_53_55_56_54_2_2367847.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_45_2-3_2288832.pcd'
#       LABEL: 'latest_label_12/label_45_2-3_2288832.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_2_7_0-1_3087431.pcd'
#       LABEL: 'latest_label_12/combined_2_7_0-1_3087431.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_45_2-3_2288832.pcd'
#       LABEL: 'latest_label_12/label_45_2-3_2288832.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_49_2_3102340.pcd'
#       LABEL: 'latest_label_12/label_49_2_3102340.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_34_33_4-5_4837459.pcd'
#       LABEL: 'latest_label_12/combined_34_33_4-5_4837459.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_5_0_3663257.pcd'
#       LABEL: 'latest_label_12/label_5_0_3663257.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_35_43_2_3878903.pcd'
#       LABEL: 'latest_label_12/combined_35_43_2_3878903.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_16_0-1-5_5665866.pcd'
#       LABEL: 'latest_label_12/label_16_0-1-5_5665866.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_30_0-3-5_5058019.pcd'
#       LABEL: 'latest_label_12/label_30_0-3-5_5058019.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_6_0_5468940.pcd'
#       LABEL: 'latest_label_12/label_6_0_5468940.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_3_8_1_3401581.pcd'
#       LABEL: 'latest_label_12/combined_3_8_1_3401581.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_17_1-4_4085920.pcd'
#       LABEL: 'latest_label_12/label_17_1-4_4085920.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_31_3-5_8167148.pcd'
#       LABEL: 'latest_label_12/label_31_3-5_8167148.npy'
#   - DATA_PATH:
#       DATA: 'pcd/combined_41_40_39_3-5_6455059.pcd'
#       LABEL: 'latest_label_12/combined_41_40_39_3-5_6455059.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_18_1-4_7312217.pcd'
#       LABEL: 'latest_label_12/label_18_1-4_7312217.npy'
#   - DATA_PATH:
#       DATA: 'pcd/label_32_1-4-5_5647419.pcd'
#       LABEL: 'latest_label_12/label_32_1-4-5_5647419.npy'
TEST:
  - DATA_PATH:
      DATA: 'pcd/combined_12_13_0_2961382.pcd'
      LABEL: 'latest_label_12/combined_12_13_0_2961382.npy'
  - DATA_PATH:
      DATA: 'pcd/label_15_0-1-3-5_7500905.pcd'
      LABEL: 'latest_label_12/label_15_0-1-3-5_7500905.npy'
  - DATA_PATH:
      DATA: 'pcd/label_25_1-4-5_9644436.pcd'
      LABEL: 'latest_label_12/label_25_1-4-5_9644436.npy'
  - DATA_PATH:
      DATA: 'pcd/combined_51_52_50_2-3_3537456.pcd'
      LABEL: 'latest_label_12/combined_51_52_50_2-3_3537456.npy'

VALIDATION:
  - DATA_PATH:
      DATA: 'pcd/label_14_0-3_5798717.pcd'
      LABEL: 'latest_label_12/label_14_0-3_5798717.npy'

  - DATA_PATH:
      DATA: 'pcd/combined_19_26_4-5_3790928.pcd'
      LABEL: 'latest_label_12/combined_19_26_4-5_3790928.npy'

  - DATA_PATH:
      DATA: 'pcd/label_22_0-1-3-5_12542709.pcd'
      LABEL: 'latest_label_12/label_22_0-1-3-5_12542709.npy'

  - DATA_PATH:
      DATA: 'pcd/label_29_0-3_5016162.pcd'
      LABEL: 'latest_label_12/label_29_0-3_5016162.npy'
