TRAIN:
  MODEL_NAME: 'UNet' 
  OPTIMIZER: 'SGD'
  MAX_WORKERS: 4 
  LEARNING_RATE: 0.12 #
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.00001
  NESTEROV: False
  BATCH_SIZE: 4 #
  MAX_EPOCH: 50
  SCHEDULER: step
  LEARNING_RATE_CLIP: 0.00001
  STEP_SIZE: 15 #
  LEARNING_RATE_DECAY: 0.5


  IS_PRETRAINED: False 
  PRETRAINED_MODEL_PATH: checkpoints/pointnet2_MT.t7

  OUTPUT_DIR: log/
  DROPOUT_RATE: 0.7 

  LOSS_FUNCTION: 'ConsistencyLoss' 
  TRAIN_IGNORE_LABEL: 100 
  CONSISTENCY_LOSS_EPOCH: 100 #
  REG_FUNC: 'relu2'

  DATASET: 'Campus3D'

  CONSISTENCY_LOSS_WEIGHT:
    - 1
    - 1
  LAYER_WEIGHTS:
    - 1
   # - 1
   # - 1
    #- 1

DEVICES:
  GPU_ID: 
    - 0
  SEED: 1

