MAIN_DATA_PATH: '/root/autodl-tmp/PointCloudSegBase/data/grid_0.200'
MAIN_LABEL_PATH: '/root/autodl-tmp/PointCloudSegBase/data/grid_0.200'
TRAIN:
  - DATA_PATH:
      DATA: 'birmingham_block_0.pcd'
      LABEL: 'birmingham_block_0.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_3.pcd'
      LABEL: 'birmingham_block_3.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_4.pcd'
      LABEL: 'birmingham_block_4.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_6.pcd'
      LABEL: 'birmingham_block_6.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_7.pcd'
      LABEL: 'birmingham_block_7.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_9.pcd'
      LABEL: 'birmingham_block_9.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_10.pcd'
      LABEL: 'birmingham_block_10.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_11.pcd'
      LABEL: 'birmingham_block_11.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_12.pcd'
      LABEL: 'birmingham_block_12.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_13.pcd'
      LABEL: 'birmingham_block_13.npy'
  # segment
  - DATA_PATH:
      DATA: 'cambridge_block_0.pcd'
      LABEL: 'cambridge_block_0.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_1.pcd'
      LABEL: 'cambridge_block_1.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_2.pcd'
      LABEL: 'cambridge_block_2.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_3.pcd'
      LABEL: 'cambridge_block_3.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_4.pcd'
      LABEL: 'cambridge_block_4.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_6.pcd'
      LABEL: 'cambridge_block_6.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_8.pcd'
      LABEL: 'cambridge_block_8.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_9.pcd'
      LABEL: 'cambridge_block_9.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_12.pcd'
      LABEL: 'cambridge_block_12.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_13.pcd'
      LABEL: 'cambridge_block_13.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_14.pcd'
      LABEL: 'cambridge_block_14.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_17.pcd'
      LABEL: 'cambridge_block_17.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_18.pcd'
      LABEL: 'cambridge_block_18.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_19.pcd'
      LABEL: 'cambridge_block_19.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_20.pcd'
      LABEL: 'cambridge_block_20.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_21.pcd'
      LABEL: 'cambridge_block_21.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_23.pcd'
      LABEL: 'cambridge_block_23.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_25.pcd'
      LABEL: 'cambridge_block_25.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_26.pcd'
      LABEL: 'cambridge_block_26.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_28.pcd'
      LABEL: 'cambridge_block_28.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_32.pcd'
      LABEL: 'cambridge_block_32.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_33.pcd'
      LABEL: 'cambridge_block_33.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_34.pcd'
      LABEL: 'cambridge_block_34.npy'

TEST:
  - DATA_PATH:
      DATA: 'birmingham_block_0.pcd'
      LABEL: 'birmingham_block_0.npy'

VALIDATION:
  - DATA_PATH:
      DATA: 'birmingham_block_1.pcd'
      LABEL: 'birmingham_block_1.npy'
  - DATA_PATH:
      DATA: 'birmingham_block_5.pcd'
      LABEL: 'birmingham_block_5.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_7.pcd'
      LABEL: 'cambridge_block_7.npy'
  - DATA_PATH:
      DATA: 'cambridge_block_10.pcd'
      LABEL: 'cambridge_block_10.npy'
